package Basic_Projects;


import java.util.Random;
import java.util.Scanner;
public class RockPaperScissorGame {

// Did you notice the following flow for the game?
// There are 3 rounds in the game
// For each round - the following steps happen
// We first take the user option
// We check whether the user has given the correct option. If the option is incorrect, we prompt the user to give the correct option
// We generate a random option for the computer
// We compare the user option to the option generated by the computer
// We update the score for the round
// At the end of the 3 rounds, we declare the overall winner
    public static void main(String[] args) {

        Scanner sc=new Scanner(System.in);

        // step-1 taking input from user and vlidating it..

        
        // Step-2 genrating random option for computer

        
        // step-3 Comapre & declare a result of each round
        String Winner=Compare(sc);
        // step-4 declare the result of game
        System.out.println("Result: "+Winner);
    }
    public static String Compare(Scanner sc){

        int rounds=1;
        int user=0;
        int computer=0;
        while(rounds!=4){
            System.out.println("Round "+rounds);
            String input=UserInput(sc);
            String ComputerSelection=Selection();
      
            if(input.equals("rock") && ComputerSelection.equals("scissor")){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("Congratulaions! You Win The Round");
                user++;
            }
            else if(input.equals("paper") && ComputerSelection.equals("scissor")){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("Computer Wins The Round");
                computer++;
            }
            else if(input.equals("scissor") && ComputerSelection.equals("rock")){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("Computer Wins The Round");
                computer++;
            }
            else if(input.equals("scissor") && ComputerSelection.equals("paper")){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("Congratulaions! You Win The Round");
                user++;
            }
            else if(input.equals("paper") && ComputerSelection.equals("rock")){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("Congratulaions! You Win The Round");
                user++;
            }
            else if(input.equals("rock") && ComputerSelection.equals("paper")){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("Computer Wins The Round");
                computer++;
            }
            else if(input.equals(ComputerSelection)){
                System.out.println("You Chose:"+" "+input);
                System.out.println("Computer Chose:"+" "+ComputerSelection);
                System.out.println("it's a tie!");
            }
            rounds++;
        }
        if(user>computer)return "Congratulations You Win the Game!!";
        else if(user<computer) return "Computer Wins You Loose The Game";
        return "It,s a tie.";
    }
    public static String UserInput(Scanner sc){
        
        System.out.print("Enter Your Choice(Rock,Paper,Scissor):");
        
        // Taking UserInput And Validating it..
        String input=sc.nextLine().trim().toLowerCase();

        while(!(input.equals("rock") || input.equals("paper")||input.equals("scissor"))){
            System.out.print("Enter The Correct Selction:");
            input=sc.nextLine();
        }
        return input;
    }

    public static String Selection(){
        
        String[] Str={"rock","paper","scissor"};
        
        // Generate a random number from [0,2]..

        Random random=new Random();
        int randomNumber=random.nextInt(3);
        return Str[randomNumber].trim().toLowerCase();
    }
}
